# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdbx < Formula
  desc "Zero-knowledge file sharing CLI — encrypt, share, self-destruct"
  homepage "https://securedbx.com"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AntonAks/securedbx/releases/download/v1.1.0/sdbx_darwin_amd64.tar.gz"
      sha256 "b532f422a734db2ab1321a695832168419f0f58990bb0a91bfffc95f47336ce9"

      define_method(:install) do
        bin.install "sdbx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AntonAks/securedbx/releases/download/v1.1.0/sdbx_darwin_arm64.tar.gz"
      sha256 "ad87f57599ceefc2252db1fe63baa3bb56b748f425e8bc7c0e89b730b67aee4c"

      define_method(:install) do
        bin.install "sdbx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntonAks/securedbx/releases/download/v1.1.0/sdbx_linux_amd64.tar.gz"
      sha256 "3f7a80772f6cfc6099906a365ac196185c9cd6225bba04ae003d484a6bc75e5b"
      define_method(:install) do
        bin.install "sdbx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntonAks/securedbx/releases/download/v1.1.0/sdbx_linux_arm64.tar.gz"
      sha256 "3fe1a58f740319fb8bb1290e32027b636747fb45177d9d7c7fd84492c81cd098"
      define_method(:install) do
        bin.install "sdbx"
      end
    end
  end

  test do
    system "#{bin}/sdbx", "version"
  end
end
